### ISSUE TITLE
Skyblock world generating terrain

### ISSUE THREAD

**Issue by ImLuze** [skyrising/skyblock#13]
I've downloaded the Scicraft skyblock world a couple months ago when it first released. I recently upgraded to 1.15.2. When I create a new skyblock world in minecraft 1.15.2 the world generation seems to work fine. But my 1.14 world seems to generate the original terrain in newly generated chunks. Is there something I can do to get the skyblock generation back in my older world while still playing minecraft 1.15.2? (and ideally remove the generated chunks of original terrain?)

**Comment by ImLuze** [comment]
The world generation seems to be reset to `default` after migrating to 1.15.2. I've manually set it back to `skyblock` by edited my `level.dat` file and this seems to fix the issue for newly generated chunks. I'll see if I can delete the chunks who have already been generated later this week. Other than that, thank you for your work on this amazing mod.

**Comment by skyrising** [comment]
Yes, that's a common issue that I can't solve. If you load a skyblock world without the skyblock mod at any time it will reset to `default`
