### ISSUE TITLE
1.16 snapshots dont work

### ISSUE THREAD

**Issue by razgriz5000** [skyrising/skyblock#14]
Is there plans to update this for 1.16?  I know 1.16 is not complete, just curious.  

[1.16-snapshot errors.txt](https://github.com/skyrising/skyblock/files/4728093/1.16-snapshot.errors.txt)

**Comment by Vresod** [comment]
Mod still does not work in 1.16.1.

**Comment by skyrising** [comment]
QuickCarpet version updated, @DeadlyMC will update the fabric-carpet version soon
