### ISSUE TITLE
Please build Skyblock for 1.16 with fabric-carpet

### ISSUE THREAD

**Issue by mrvn** [skyrising/skyblock#16]
I'm playing "SkyBlock for fabric-carpet and Minecraft 1.15.x" with the carpet-extra mod for the autoCraftingDropper support (the autoCraftigTable in quickcarpet is too buggy to use).

Now I would like to update to 1.16 but there is only support for quickcarpet so far. Please also build a Skyblock jar for fabric-carpet for 1.16.

**Comment by QPCrummer** [comment]
Same with me

**Comment by QPCrummer** [comment]
I would like all of the feature with carpet/carpet extra on my skyblock world

**Comment by ac2302** [comment]
same here

**Comment by QPCrummer** [comment]
If you don't have enough time to make it compatible with carpet, is there a way for me to do it?

**Comment by skyrising** [comment]
> the autoCraftigTable in quickcarpet is too buggy to use

What bugs do you mean, @mrvn ? Could you open a bug report for [QuickCarpet](https://github.com/DeadlyMC/QuickCarpet114/issues)?

**Comment by DeadlyMC** [comment]
Sorry about it taking so long, the new release is out 
https://github.com/skyrising/skyblock/releases/tag/v1.2-fc
