### ISSUE TITLE
Release the Nylium!

### ISSUE THREAD

**Issue by Sillymanblah** [skyrising/skyblock#18]
I see that a change was made to the code after the latest release making it possible to trade for crimson and warped nylium blocks, however this has not been released and therefore is not a part of the download. Can you add it to the latest release @DeadlyMC?

**Comment by skyrising** [comment]
We'll update ilmango's SkyBlock server soon, I will test everything and also make a public release then.

**Comment by skyrising** [comment]
You can now download the latest build from https://github.com/skyrising/skyblock/actions/runs/217043329 (unzip and use skyblock-3.1.0-dev.20200820.160535+HEAD.jar) but I'm not sure how stable it is, should work though
