### ISSUE TITLE
No, option to generate skyblock world

### ISSUE THREAD

**Issue by 0x3444ac53** [skyrising/skyblock#20]
After installing QuickCarpet and skyblock, `World Type: Skyblock` doesn't appear as an option

**Comment by FootrottFlats** [comment]
Same.  Using: skyblock-3.0.0 and quickcarpet-2.2.0 for Fabric 1.16.1
No errors, just no skyblock option.  Using Modmenu and Skyblock and Quickcarpet both show up as installed

Tried it with 1.16.2 also, Skyblock-3.0.0 and Quickcarpet v2.4.0. Both show on modmenu but no option for skyblock

**Comment by skyrising** [comment]
Duplicate of #15, skyblock generation is now hardcoded.
