### ISSUE TITLE
skyblock carpet rules not registered to fabric-carpet

### ISSUE THREAD

**Issue by aria1th** [skyrising/skyblock#22]
moved from quickcarpet based to fabric carpet based skyblock jar.
World generates correctly, but carpet rules does not appear by /carpet command, not in list, not in category.
r
skyblock-fc-1.16.3-1.2.0.jar
fabric-carpet-1.16.3-1.4.12+v201001.jar

without carpet rule, wandering trader don't get additional trades so I think its a bug.
expected : /carpet list skyblock exist
appears:
![2020-10-10_16 39 24](https://user-images.githubusercontent.com/35677394/95649187-4255ba80-0b17-11eb-91c7-46ec624f733f.png)

**Comment by aria1th** [comment]
seems line
`public static final String CARPET_MOD = "carpet_mod";`
missing in built jar

**Comment by DeadlyMC** [comment]
You gotta make use of `/skyblock` command for the fabric-carpet version
