### ISSUE TITLE
Wandering Villager Trades

### ISSUE THREAD

**Issue by Bob-Joe-2000** [skyrising/skyblock#29]
The new wandering villager trades are not getting mixed in, so I can't progress and get lava.

**Comment by Bob-Joe-2000** [comment]
Fixed it, had to do /skyblock list

**Comment by Bob-Joe-2000** [comment]
I'm not getting any lava trades though

**Comment by skyrising** [comment]
Do `/skyblock setDefault wanderingTraderSkyblockTrades true`

**Comment by Bob-Joe-2000** [comment]
What is the chance of a lava bucket trade?

**Comment by skyrising** [comment]
1/20 I think

**Comment by Bob-Joe-2000** [comment]
Thx
