### ISSUE TITLE
Unable to store "default" value.

### ISSUE THREAD

**Issue by codesource** [skyrising/skyblock#3]
Hi,
I am using SkyBlock module with fabric-carpet and I am not able to store default value.
I get this error "Unknown rule: wanderingTraderSkyblockTrades".

It was working with old version, when skyblock commands were `/carpet skyblock ...`

I am using only the 2 module "fabric-carpet" and "skyblock" 

![image](https://user-images.githubusercontent.com/1862276/69547668-51328d80-0f96-11ea-9091-4d0e68a70205.png)

**Comment by codesource** [comment]
It seems that only the shortcut is wrong.
It should be "`/skyblock setDefault wanderingTraderSkyblockTrades true`" instead of `/carpet ...`

**Comment by DeadlyMC** [comment]
With the fabric-carpet mod everything should be handled with `/skyblock`

**Comment by codesource** [comment]
Totaly true, but the "`[change permanently?]`" shortcut use `/carpet` instead of `/skyblock` prefix

**Comment by DeadlyMC** [comment]
Its intended that it uses /skyblock or else it removes the point of an extension system

**Comment by skyrising** [comment]
I assume this is a bug in fabric-carpet suggesting the wrong command?

**Comment by DeadlyMC** [comment]
Oh i am really sorry i probs misunderstood, is it that it displays the `/carpet setDefault` setting when u press the `[change permanently?]`? If it does..yes then its a bug

**Comment by codesource** [comment]
Yes, you probably right @skyrising. 
Should I forward the report to fabric-carpet?

**Comment by skyrising** [comment]
I'd recommend that, yes
