### ISSUE TITLE
Getting gold in 1.17

### ISSUE THREAD

**Issue by Jubber4442** [skyrising/skyblock#33]
Is there any way to get gold in the 1.17 version, now that the drowned drop copper instead?

**Comment by Salmon-e** [comment]
You can duplicate lava with dripstone and use that to make a portal and farm pigmen.

**Comment by Jubber4442** [comment]
I guess, so. We started in 1.17, and haven't gotten any lava or villagers. We then needed emeralds to trade with the wandering trader, but i guess you can just kill enough vindicators to get them.

**Comment by Jubber4442** [comment]
Actually vindicators no longer spawn in patrols, meaning there is no way to get emeralds, if you haven't gotten lava before. So the only way would be foxes, and getting enough foxes to spawn would take forever.

**Comment by catiosis** [comment]
create lightning rods with the copper and convert pigs to pigmen

**Comment by Jubber4442** [comment]
Oh yeah, didn't think of that at all.

**Comment by Salmon-e** [comment]
Update ig, the way I ended up doing it was by smelting down gold armor from mobs. Wouldn't work in your case, since you don't have lava, but worked well for me and avoided the fox grinding.
