### ISSUE TITLE
only planes. 

### ISSUE THREAD

**Issue by derieziger** [skyrising/skyblock#37]
I am having a problem with the world only generating planes. even in the nether its all planes. I'm not shure what information is needed to fix this issue so just ask me for the info you need

**Comment by PrivacyPolicy** [comment]
The latest change in the 1.18 branch fix this issue. If you want, you can download the code and build 3.2.1 manually (~readme has steps~). Otherwise you’ll have to wait until it’s properly released. @skyrising what is the usual process for a release to get created?

**Comment by skyrising** [comment]
Made a new release: https://github.com/skyrising/skyblock/releases/tag/v3.2.1
