### ISSUE TITLE
Oceans are replaced.

### ISSUE THREAD

**Issue by Mizaar** [skyrising/skyblock#38]
All ocean biomes are replaced by plain bioms. Beaches are removed aswell. No turtle eggs and corall fans for me. :(
Minecraft 1.18,1, mod 3.2.0
P.S. Do custom trades still exist in the mod? I've checked about a hundred traders and all have vanilla ony trades.

**Comment by 15shadow** [comment]
It was know issue and it was fixed in 3.2.1 mod version.
P.S. When you want custome trades you must enable it. The easiest way is to write /carpet click on skyblock and true option on wandertrading.
