### ISSUE TITLE
Trees disappearing 

### ISSUE THREAD

**Issue by ToastHead2** [skyrising/skyblock#4]
Hello,

I was playing skyblock when i noticed i had forgotten to put in the skyblock file. So that meant that the void stopped after 250 blocks. I already made a nice startbase so I saved a schematic in world edit, and saved the player logs. When i reinstalled everything and put the player logs in and copied back the base and started to play, something strange happend. When my trees grew some of them just started dismantling themselves.

A short video showing you what happens:
[https://youtu.be/KH82Td_oyLQ](url)
(if links doesn't work copy and paste in browser)
I hope someone can help me.

**Comment by skyrising** [comment]
Which mods do you have installed?

**Comment by ToastHead2** [comment]
- fabric-api-0.4.25+build.282-1.15
- fabric-carpet-1.15.1-1.3.1+v191212 (1)
- skyblock-fc-1.15-1.1.0
- modmenu-1.8.2+build.18

**Comment by ToastHead2** [comment]
Mobs also don't drop anything except a skeleton that sometimes drops a bow

**Comment by skyrising** [comment]
@DeadlyMC anything in fabrc-carpet or skyblock-fc that could cause this?

**Comment by ToastHead2** [comment]
i tried some more things but i think i messed something up with the files or something.
There are no crafting recipies, nothing drops anything, not even mining. 
I guess i'll just start over.

Sorry for wasting your time with this.

**Comment by skyrising** [comment]
Seems like all the loot tables are messed up. Probably also the block tags, which would mean logs aren't recognized and leaves decay

**Comment by ToastHead2** [comment]
Thanks!

**Comment by DeadlyMC** [comment]
Both **skyblock-fc** and **skyblock-qc** basically have the same code.
