### ISSUE TITLE
Mod requires Carpet, not QuickCarpet

### ISSUE THREAD

**Issue by SINBRO** [skyrising/skyblock#5]
When only Quickcarpet (2.1.0) and Skyblock (1.1.1) on 1.15.2 fabric are installed, minecraft doesn't launch with modloading error like "Skyblock needs carpet"
With Carpet everything works.
Not like I mind it, but maybe you should fix the description.

**Comment by skyrising** [comment]
You're using the fabric-carpet version, which (obviously) requires fabric-carpet.
Use the second download on the releases page for quickcarpet
