### ISSUE TITLE
Overworld has no blocks but Nether dimension does

### ISSUE THREAD

**Issue by cakemonitor** [skyrising/skyblock#6]
I've been playing a Skyblock map using fabric server and mod files: fabric-carpet-1.15.2-1.3.9+v200206.jar and skyblock-fc-1.15.2-1.1.1.jar. Though, NB: I actually started this game as a single player world using slightly older versions of the same mods, and then later copied the world files to a server to make it easier to play with friends, and also upgraded the server & mods once v1.15.2 was available.

I installed the fabric server using the universal installer .jar file, and set it up alongside a vanilla Minecraft 1.15.2 server which has been renamed to "server.jar". The two mods named above were copied into a "mods" directory at the root of the server, and as per the instructions in the readme.md I edited server.properties and changed `level-type=default` to `level-type=skyblock`.

Everything was working just fine until we entered the Nether and saw it was generating blocks in the Nether dimension as per a vanilla Minecraft game. At that point I stopped the server and made a backup of the world. Then as a test I edited server.properties and changed just the level-name entry to read `level-name=Test`, and launched the server again. This created a new and empty Skyblock world so I went into creative mode and made a quick dirt platform and Nether portal. When I stepped through that portal the Nether was empty - exactly as expected. Just to be sure I flew out several hundred blocks and confirmed nothing was generating. Then I stopped the server and deleted the DIM-1 folder from my original Skyblock world (which if I understand right is where the Nether data is saved) and copied over the DIM-1 folder from the new Test world. I then restored `level-name=Skyblock` in server.properties, and started the server once more. When I first entered the Nether it appeared empty and when I flew in the same direction as I did in the Test world it stays empty, but if I go further or travel in any other direction it starts generating Nether blocks again! To be sure that this is only happening in the Nether I went back into the Overworld and flew nearly a thousand blocks in a direction which we had not previously explored, and it did not generate any Overworld blocks.

What do I need to do to get the server to run my existing Skyblock world which contains all of our Overworld buildings, items, and achievements but to not generate any blocks within the Nether dimension? And is there anything I need to do to be sure the End dimension will be empty too?

Thanks!

**Comment by skyrising** [comment]
Check the level.dat file with an NBT editor to see if the generator is also set to skyblock there. That's the setting that actually matters, since for existing worlds the one in server.properties is ignored.

**Comment by cakemonitor** [comment]
Thank you so much! :)
It was indeed set to default so I've changed it to skyblock and now everything is working well again.
