### ISSUE TITLE
Spawning columns information is incorrect (so farms don't farm)

### ISSUE THREAD

**Issue by SINBRO** [skyrising/skyblock#7]
I noticed that rates of my y0 slime farm were dramatically bad. After some research, I used MiniHud option "Spawnable columns height overlay", which showed columns that tops were like there was normal terrain. 
![image](https://user-images.githubusercontent.com/36847049/75617895-55161300-5b76-11ea-84b4-55a3b52836e7.png)
Ater I filled some area on the top of the world with stone and then removed it, all columns identified correctly.
![image](https://user-images.githubusercontent.com/36847049/75617882-1da76680-5b76-11ea-889e-a1b3bd8039cc.png)
P.s. 1.15.2 skyblock-fc-1.15.2-1.1.1 with fabric-carpet-1.15.2-1.3.9+v200206

**Comment by SINBRO** [comment]
Wow, I'm really sorry. I checked some other areas of the World and it seems that the problem exists only in pre-generated area of the world which I got from Ilmango.

**Comment by skyrising** [comment]
Yes, this was an issue in early versions of the mod, but should be working correctly now.
