### ISSUE TITLE
Not getting custom trades - fabric-carpet-1.15.2-1.3.16

### ISSUE THREAD

**Issue by EichenherzMo** [skyrising/skyblock#8]
I spawned in like a thousnad wandering traders and i havent got any of the custom trades

**Comment by JoaquimDaPonte** [comment]
Same here

**Comment by DeadlyMC** [comment]
Do you have the carpet rule on

**Comment by MoSchaub** [comment]
Which rule?

**Comment by Fish-XD** [comment]
> 你有地毯的规定吗

Can you make it clear?

**Comment by FrozenFireNinja** [comment]
Do /carpet, click the blue "[skyblock]" button, and change settings from there.
